Tests: improve unit tests coverage
lidofinance/aragon-apps pull request #10
Opened 2022-06-06 10:17 UTC by TheDZhon

**WIP**

2022-06-07 07:49 UTC, folkyatina reviewed
Only one minor notice and LGTM.

2022-06-07 07:49 UTC, folkyatina commented on apps/voting/test/voting.js
> +        it('getVotePhase works', async () => {
Can check phase in `getVote()` as well

2022-06-07 08:31 UTC, arwer13 requested changes
LGTM 👍 , except for `unsafelyChangeVoteTime` lacking test for `auth(UNSAFELY_MODIFY_VOTE_TIME_ROLE)` authentication (sadly, it's not being displayed in the coverage report)

2022-06-07 16:13 UTC, TheDZhon commented
The code has been updated, thank you for the findings :100: 

![image](https://user-images.githubusercontent.com/961317/172430335-dff9189d-64e9-4172-9cca-65973b9878b5.png)

2022-06-08 09:52 UTC, folkyatina approved these changes

2022-06-10 12:10 UTC, arwer13 approved these changes

2022-06-10 12:14 UTC, merged